### PR TITLE
Update PHG4CylinderDetector.cc

### PR DESCRIPTION
**Pull request by zulkaidaakbar**
I modified the packing fraction from 90% to 60%

### CODE REVIEW

**Comment by zulkaidaakbar** [comment]
We change the packing fraction from 90% to 60% since 90% packing fraction is not realistic. 60% is the typical packing fraction for NH3-beads target immersed in liquid Helium. We did CAT scan at UVA using plastic bead that mimic NH3 bead and we get really close to 60%

**Review by liuk — APPROVED** [review]

**Comment by liuk** [comment]
Sorry I clicked the approve button too fast.

If we think 60% packing fraction is still a number that might change in the future, maybe we should provide a interface to allow user to change it instead of hard-coding it?

**Comment by knakano0524** [comment]
@zulkaidaakbar Can you update the numbers described in the comment block above?

By writing this message, I realized that the quantity expected here is the percentage in *weight* and thus the orignal numbers "90:10" should be correct.  I understand "60:40" are the percentage in *volume*.

**Comment by zulkaidaakbar** [comment]
Hi All,

I am sorry for not checking. I just checked and @knakano0524 is correct. The percentage in Geant AddMaterial is mass fraction and not packing (volume) fraction. I calculated and found that the mass fraction for lHe is 10.03%. So, I guess the present number (10% and 90%) is correct. 

@liuk : I think we will do one CAT-scan measurement so there will be one time change in the future. Maybe hard-coded is still fine. 

@knakano0524 :  "Can you update the numbers described in the comment block above?" I am sorry, what number in what comment block?

**Comment by knakano0524** [comment]
I meant the comment block just above the lines you changed;
```
// M_He = 0.4*0.145 = 0.058 g; M_NH3 = 0.6*0.867 = 0.520 g, M/rho = 0.578
// f_M_He = 10.0%, f_M_NH3 = 90.0%
```
You no longer need to update them.

I remember the UVA group wants to change the material to completely different objects, like Air and 100% LHe.  Such flexible interface might be still wanted.

**Comment by zulkaidaakbar** [comment]
Sorry, I accidentally clicked the request to re-review. 
@knakano0524 , thanks for inviting me to be a member. But I still don't see a button to assign reviewer here.

**Comment by liuk** [comment]
It seems we don't need to change the packing fraction for now. Should I just close this PR?

**Comment by zulkaidaakbar** [comment]
Yes, I we can close this pull request. Thank you

**Pull request closed without merging**
