### PR TITLE
small fix and default setting

### PR DESCRIPTION
**Pull request by HaiwangYu**
- small linking fix
- add DP to default sim list

### CODE REVIEW

**Comment by HaiwangYu** [comment]
Sorry I pushed n commit [82f8e78](https://github.com/E1039-Collaboration/e1039-core/pull/49/commits/82f8e780a41e24cdf962bbb7c114ef643dc7882a) incidentally to this branch. It is to update the event display for DP.

**Comment by HaiwangYu** [comment]
- Wire position LUT fix
- Digitization compatible with DP
- Event display compatible with DP

**Comment by knakano0524** [comment]
Thank you for examining the update.   Your changes seem reasonable.  Please merge them into master branch once you finish your updates.  Particularly I see the changes in GeomSvc.cxx were what I should have done.  Thank you again for catching them.

**Comment by HaiwangYu** [comment]
Thanks for confirm this. I will merge both #49 and #48 into the master.

**Pull request merged**
